---
- hosts: all
  become: yes
  vars_files:
    - vars/var.yml

  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']

    - name: add apt-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Enable universe repository
      apt_repository:
        repo: "{{ item }}"
      loop:
        - "deb http://archive.ubuntu.com/ubuntu/ focal universe"
        - "deb http://archive.ubuntu.com/ubuntu/ focal-updates universe"
        - "deb http://security.ubuntu.com/ubuntu/ focal-security universe"

    - name: Install package installer
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'python3-dev', 'python3-pip']

    - name: install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes

    - name: add userpermissions
      shell: "usermod -aG docker root"

    - name: install python sdk
      become_user: root
      pip:
        name:
          - docker
          - docker-compose

    - name: Create docker/wordpress directory
      file:
        path: /opt/docker/wordpress
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Create docker-compose file
      template:
        src: docker-compose.yml.j2
        dest: /opt/docker/wordpress/docker-compose.yml
        owner: root
        group: root
        mode: 0644

    - name: Run docker-compose up -d
      shell: docker-compose up -d
      args:
        chdir: /opt/docker/wordpress/